FROM mcr.microsoft.com/playwright:v1.52.0-noble

WORKDIR /app

RUN npx playwright install chrome
RUN npx playwright install msedge

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN npm run build

CMD ["npx", "playwright", "test"]
